"""create_like_posts

Revision ID: 731418dfcd6c
Revises: a0dd19d2a3fb
Create Date: 2018-11-29 16:15:50.393461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '731418dfcd6c'
down_revision = 'a0dd19d2a3fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like_posts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like_posts')
    # ### end Alembic commands ###
